#!/usr/bin/env bash

# Create a regex for a conventional commit.
convetional_commit_regex="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z \-]+\))?!?: .+$"

# Get the commit message (the parameter we're given is just the path to the
# temporary file which holds the message).
commit_message=$(cat "$1")

# Check the message, if we match, all good baby.
if [[ "$commit_message" =~ $convetional_commit_regex ]]; then
   exit 0
fi

# Uh-oh, this is not a conventional commit, show an example and link to the spec.
echo -e "\e[31mA mensagem do commit não está de acordo com Conventional Commit standard\e[0m"
echo "Um exemplo de mensagem válida é: "
echo "  feat(login): adicionar o botão 'Esqueci a senha'"
echo "Mais informações em: https://www.conventionalcommits.org/en/v1.0.0/#summary"
exit 1