name: CD
on:
  push:
    branches: [main]
jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK    
        uses: actions/setup-java@v1      
        with:        
          java-version: 17
      - name: Run Tests
        run: mvn -B test

  bump:
    name: Bump version
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Configure bot
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "CD bot"

      - name: Bump files
        run: npx @dwmkerr/standard-version --packageFiles pom.xml --bumpFiles pom.xml

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          tags: true

  build:
    name: Build
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure bot
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "CD bot"

      - name: Pull
        run: |
          git pull origin main

      - name: Set up JDK    
        uses: actions/setup-java@v1      
        with:        
          java-version: 17
      - name: Build with Maven      
        run: mvn clean install

      - name: Get project version
        run: echo "VERSION=$(grep -m 2 '<version>' pom.xml | awk -F'[><]' '{print $3}' | awk 'NR==2')" >> $GITHUB_ENV

      - name: Create version artifact
        run: |
          mkdir -p artifact
          echo $VERSION > artifact/version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v2
        with:
          name: version-artifact
          path: artifact/version.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build image and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: 'arthurkj/hello-world-api:${{ env.VERSION }}'
          context: .
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure bot
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "CD bot"

      - name: Pull
        run: |
          git pull origin main

      - name: Download version artifact
        uses: actions/download-artifact@v2
        with:
          name: version-artifact
          path: artifact

      - name: Get project version
        run: echo "VERSION=$(cat artifact/version.txt)" >> $GITHUB_ENV

      - name: Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1

      - name: Update k8s
        run: |
          cd k8s
          kustomize edit set image hello-world-api-image=arthurkj/hello-world-api:${{ env.VERSION }}
          cat kustomization.yaml

      - name: Commit
        run: |
          git commit -am "change image tag"

      - name: Push
        uses: ad-m/github-push-action@master
